<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Showmore_button</name>
   <tag></tag>
   <elementGuidId>a63a415c-34af-43f9-9f9b-650d7ec1d7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@ng-disabled='vm.loadingMore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@ng-disabled='vm.loadingMore']</value>
   </webElementProperties>
</WebElementEntity>
